[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "huawei-manager"
dynamic = ["version"]
dependencies = [
    "netmiko~=4.4.0",
    "python-dotenv~=1.0.1",
    "cryptography~=44.0.0",
    "pyyaml~=6.0.2",
    "PySide6~=6.10.1",
    "bcrypt~=4.2.1",
]

[tool.setuptools.dynamic]
version = {attr = "huawei_manager.__version__"}

[project.optional-dependencies]
dev = ["pytest~=8.3.4", "pytest-cov~=6.0.0", "pytest-qt~=4.4.0", "ruff~=0.8.6", "pyright~=1.1.391"]
vault = ["hvac~=2.2.0"]
aws = ["boto3~=1.35.0"]

[tool.pyright]
venvPath = "."
venv = ".venv"
reportOptionalMemberAccess = "warning"
reportAttributeAccessIssue = "warning"
reportMissingTypeStubs = "warning"
reportUnknownVariableType = "warning"
reportUnknownMemberType = "warning"
reportUnknownParameterType = "warning"
reportMissingParameterType = "warning"
reportMissingTypeArgument = "warning"

[tool.ruff]
target-version = "py312"
line-length = 100
select = ["E", "F", "W", "I", "UP"]
ignore = []
fixable = ["E", "F", "W", "I"]
