"""AppCoreProtocol — type-safe contract for mixin inheritance.

Contrato estrutural único da janela principal: todos os mixins
(Shortcuts, AppState, PageBuilder, EventHandlers, Threading) acessam
membros uns dos outros anotando ``self: AppCoreProtocol``. Manter este
arquivo em sincronia com as implementações é o que mantém o pyright
estrito sem ciclos de import em runtime.
"""
from __future__ import annotations

import threading
from collections import deque
from collections.abc import Callable, Sequence
from concurrent.futures import ThreadPoolExecutor
from typing import TYPE_CHECKING, Protocol, runtime_checkable

from huawei_manager.device_models import Device
from huawei_manager.sdn_controller.authz import SessionTracker
from huawei_manager.sdn_controller.bus import IEventBus
from huawei_manager.sdn_controller.dryrun import DryRunEngine
from huawei_manager.sdn_controller.southbound import SouthboundProtocol
from huawei_manager.sdn_controller.validator import CommandValidator
from huawei_manager.services.device_service import DeviceService

if TYPE_CHECKING:
    from PySide6.QtGui import QPixmap
    from PySide6.QtWidgets import (
        QComboBox,
        QLabel,
        QLineEdit,
        QListWidget,
        QListWidgetItem,
        QRadioButton,
        QStackedWidget,
        QTextEdit,
        QVBoxLayout,
        QWidget,
    )

    from huawei_manager.agents import AgentResult
    from huawei_manager.agents.watcher import Watcher
    from huawei_manager.sdn_controller.core import ControllerCore
    from huawei_manager.sdn_controller.drivers.router import RouterDriver
    from huawei_manager.sdn_controller.event_queue import Event
    from huawei_manager.sdn_controller.session_factory import SSHSessionFactory
    from huawei_manager.services import ServiceDef
    from huawei_manager.session import NetmikoSession
    from huawei_manager.topology import TopologyCanvas
    from huawei_manager.widgets.neon_button import ActionButton, NeonButton


@runtime_checkable
class AppCoreProtocol(Protocol):
    # ── Núcleo / SDN ────────────────────────────────────────────────
    _sb: SouthboundProtocol
    session: NetmikoSession
    _target_device: Device | None

    _event_queue: IEventBus
    _session_tracker: SessionTracker
    _access_level: str
    _mock_mode: bool

    _ui_queue: deque[Callable[[], object]]
    _io_executor: ThreadPoolExecutor
    _cpu_executor: ThreadPoolExecutor
    _event_drop_count: int

    _devices: list[Device]
    _devices_lock: threading.Lock
    _topo_canvas: TopologyCanvas | None
    _watcher: Watcher
    _device_service: DeviceService

    _cmd_validator: CommandValidator | None
    _dry_run: DryRunEngine | None
    _controller: ControllerCore
    _drv: RouterDriver

    _auth_overlay: QWidget | None
    _admin_attempts: int
    _admin_locked_until: float
    _session_factory: SSHSessionFactory
    _shutdown: bool
    _sysview_var: bool
    ADMIN_MAX_ATTEMPTS: int
    ADMIN_LOCKOUT_SECS: int
    backup_path: str

    content: QWidget | None

    # ── Layout / navegação ──────────────────────────────────────────
    sidebar: QWidget
    content_layout: QVBoxLayout
    pages: dict[str, QWidget]
    _page_container: QStackedWidget | None
    status_dot: QLabel
    status_lbl: QLabel
    clock_lbl: QLabel
    conn_btn: ActionButton
    theme_btn: ActionButton | None
    _nav_buttons: dict[str, NeonButton]
    _active_btn: NeonButton | None
    _current_page: str | None
    _PAGE_KEYS: list[str]
    _logo_pixmap: QPixmap | None

    route_filter_var: str
    _route_filter_cb: QComboBox
    _admin_btn: ActionButton
    _backup_entry: QLineEdit | None
    _backup_fmt_lbl: QLabel
    _device_target_lbl: QLabel

    # ── Páginas: saídas de texto ────────────────────────────────────
    out_config: QTextEdit | None
    out_route: QTextEdit | None
    out_arp: QTextEdit | None
    out_info: QTextEdit | None
    out_cmd: QTextEdit | None
    out_backup: QTextEdit | None
    _cmd_editor: QTextEdit | None

    # ── Dashboard ───────────────────────────────────────────────────
    _dash_conn_status: QLabel | None
    _dash_conn_host: QLabel | None
    _dash_device_online: QLabel | None
    _dash_device_offline: QLabel | None
    _dash_device_unknown: QLabel | None
    _dash_audit_text: QTextEdit | None
    _dash_shortcut_btns: dict[str, str]

    # ── Topologia / devices ─────────────────────────────────────────
    _device_info_lbl: QLabel | None
    _device_status_lbl: QLabel | None

    # ── Serviços ────────────────────────────────────────────────────
    _svc_output: QTextEdit | None
    _svc_cat_cb: QComboBox | None
    _svc_cat_var: str
    _svc_mode_var: str
    _svc_listbox: QListWidget | None
    _svc_detail_frame: QWidget | None
    _svc_device_lbl: QLabel | None
    _svc_type_lbl: QLabel | None
    _svc_status_lbl: QLabel | None
    _svc_param_entries: dict[str, QLineEdit]
    _svc_services: list[ServiceDef]
    _svc_current_svc: ServiceDef | None

    # ── Comandos / templates ────────────────────────────────────────
    _tpl_cmd_map: dict[str, str]
    _tpl_listbox: QListWidget

    # ── Manutenção ──────────────────────────────────────────────────
    _manut_output: QTextEdit | None
    _manut_summary: QTextEdit | None
    _manut_filter: str
    _manut_rb_group: list[QRadioButton]
    _mode_btn: ActionButton
    _watcher_btn: ActionButton
    _cancel_event: threading.Event | None
    _last_manut_results: Sequence[AgentResult]
    _watcher_results: Sequence[AgentResult] | None
    _devices_gen: int

    # ════════════════════════════════════════════════════════════════
    #  MÉTODOS
    # ════════════════════════════════════════════════════════════════

    # ── Threading / helpers ─────────────────────────────────────────
    def _dispatch(self, fn: Callable[[], object], *, sdn: bool = False) -> None: ...
    def _on_sdn_event(self, ev: Event | None) -> None: ...
    def _spawn_io(self, fn: Callable[..., object], *args: object) -> None: ...
    def _spawn_cpu(self, fn: Callable[..., object], *args: object) -> None: ...
    def _write(self, widget: QTextEdit | None, text: str) -> None: ...
    def _safe_write(self, widget: QTextEdit | None, text: str) -> None: ...
    def _loading(self, widget: QTextEdit | None, msg: str) -> None: ...
    def _run(self, func: Callable[[], object]) -> None: ...

    # ── Navegação / páginas ─────────────────────────────────────────
    def _show_page(self, key: str) -> None: ...
    def _make_page(self, key: str) -> QWidget: ...
    def _page_layout(self, p: QWidget) -> QVBoxLayout: ...
    def _page_title(
        self, parent: QWidget, title: str, color: str, subtitle: str = ""
    ) -> None: ...
    def _css_label(
        self, color: str, bg: str = "", font_size: int = 12, bold: bool = False
    ) -> str: ...
    def _rebuild_page(self, key: str) -> None: ...
    def _toggle_command_palette(self) -> None: ...
    def _toggle_theme(self) -> None: ...

    # ── Estado / tema / sessão ──────────────────────────────────────
    def _set_status(self, text: str, color: str) -> None: ...
    def _set_conn_btn(self, text: str = "", disabled: bool = False) -> None: ...
    def _tick_dashboard(self) -> None: ...
    def _tick_devices(self) -> None: ...
    def _check_session_timeout(self) -> None: ...
    def _on_watcher_update(self, results: Sequence[AgentResult]) -> None: ...
    def _rebuild_manutencao_if_active(self) -> None: ...
    def _refresh_dashboard(self) -> None: ...

    # ── Shortcuts ───────────────────────────────────────────────────
    def _setup_bindings(self) -> None: ...
    def _on_enter(self) -> None: ...
    def _on_ctrl_shift_enter(self) -> None: ...
    def _on_ctrl_d(self) -> None: ...
    def _on_ctrl_l(self) -> None: ...
    def _on_ctrl_q(self) -> None: ...
    def _on_ctrl_shift_a(self) -> None: ...
    def _on_f5(self) -> None: ...
    def _on_ctrl_tab(self) -> None: ...
    def _on_ctrl_shift_tab(self) -> None: ...
    def _on_escape(self) -> None: ...

    # ── Auth / conexão ──────────────────────────────────────────────
    def _show_auth_dialog(self) -> None: ...
    def _require_access(self, level: str = "admin") -> bool: ...
    def _get_selected_device(self) -> Device | None: ...
    def _ensure_device_ready(self, action: str) -> Device | None: ...
    def _prompt_no_devices(self, action: str) -> None: ...
    def _toggle_connect(self) -> None: ...
    def _do_connect(self, on_success_fmt: str, on_error_msg: str) -> None: ...
    def _connect_with_device(self, device: Device) -> None: ...

    # ── Fetch ───────────────────────────────────────────────────────
    def _fetch_config(self) -> None: ...
    def _fetch_route(self, fkey: str = "") -> None: ...
    def _fetch_arp(self) -> None: ...
    def _fetch_info(self) -> None: ...

    # ── Devices ─────────────────────────────────────────────────────
    def _refresh_devices(self) -> None: ...
    def _update_devices_ui(self, devices: list[Device]) -> None: ...
    def _show_device_dialog(self, device: Device | None = None) -> None: ...
    def _delete_device(self, device: Device) -> None: ...
    def _on_device_selected(self, device: Device) -> None: ...
    def _clear_device_target(self) -> None: ...

    # ── Comandos / backup ───────────────────────────────────────────
    def _get_editor_cmd(self) -> str: ...
    def _confirm_destructive(self, cmd: str) -> bool: ...
    def _run_cmd_safe(self, cmd: str = "") -> None: ...
    def _run_config_safe(self, cmd: str = "") -> None: ...
    def _exec_cmd(self, cmd: str = "") -> None: ...
    def _exec_config(self, cmd: str = "") -> None: ...
    def _do_backup(self, fmt: str = "") -> None: ...
    def _choose_backup_dir(self) -> None: ...

    # ── Serviços ────────────────────────────────────────────────────
    def _run_service(
        self, svc: ServiceDef, final_svc: ServiceDef | None = None
    ) -> None: ...
    def _validate_service(
        self, svc: ServiceDef, final_cmds: list[str]
    ) -> list[tuple[str, str]]: ...
    def _refresh_service_list(self) -> None: ...
    def _show_service_detail(self, svc: ServiceDef) -> None: ...
    def _on_svc_cat_changed(self, text: str) -> None: ...
    def _on_service_select(self, row: int) -> None: ...
    def _clear_detail_panel(self) -> None: ...
    def _build_services_info_row(self, parent: QWidget) -> None: ...
    def _build_services_filter_row(self, parent: QWidget) -> None: ...
    def _build_services_split(self, parent: QWidget) -> None: ...
    def _build_param_fields(self, parent: QWidget, svc: ServiceDef) -> None: ...
    def _build_services_page(self) -> None: ...

    # ── Builders de página ──────────────────────────────────────────
    def _build_home_page(self) -> None: ...
    def _build_config_page(self) -> None: ...
    def _build_route_page(self) -> None: ...
    def _build_arp_page(self) -> None: ...
    def _build_info_page(self) -> None: ...
    def _build_cmd_page(self) -> None: ...
    def _build_backup_page(self) -> None: ...
    def _build_topology_page(self) -> None: ...
    def _build_manutencao_page(self) -> None: ...

    # ── Manutenção ──────────────────────────────────────────────────
    def _run_agents(self) -> None: ...
    def _toggle_watcher(self) -> None: ...
    def _toggle_probe_mode(self) -> None: ...
    def _cancel_and_clear(self) -> None: ...
    def _run_setup(self, mode: str) -> None: ...
    def _run_dev_cmd(self, target: str) -> None: ...
    def _display_watcher_results(self, results: Sequence[AgentResult]) -> None: ...
    def _apply_manut_filter(self) -> None: ...
    def _on_manut_filter_toggled(self, checked: bool, value: str) -> None: ...

    # ── Templates de comando ────────────────────────────────────────
    def _on_tpl_select(self, row: int) -> None: ...
    def _on_tpl_activate(self, item: QListWidgetItem) -> None: ...

    # ── Qt (usados via self de protocolo nos mixins) ────────────────
    def close(self) -> bool: ...
    def focusWidget(self) -> QWidget | None: ...
